### ISSUE TITLE
`alias cd='rm -rfv'` seems a bit much

### ISSUE THREAD

**Issue by habibalamin** [mathiasbynens/evil.sh#15]
Maybe `alias cd='rm -rfi'`?

**Comment by avindra** [comment]
Change the cd alias already!

**Comment by habibalamin** [comment]
@avindra I don't think he's ever going to change it, barring something major. `evil.sh` is an apt name for this repository/script.

**Comment by ChristopherKing42** [comment]
How about it moves the directory to some secret location (and display a fake removal message).

**Comment by rubo77** [comment]
@benaryorg, you daddy in the readme:

>  a patch that adds rm -rfv / to evil.sh will be rejected.

But that alias is exactly that:

    cd / 

Would delete the whole disk without confirmation!

Please change that

**Comment by mathiasbynens** [comment]
Setting an alias is not the same as _executing_ that alias.

**Comment by benaryorg** [comment]
I'd like to see #45 accepted.

**Comment by benaryorg** [comment]
Or #56 which enables the (colleague of the) user to disable this behaviour easily.

**Comment by rubo77** [comment]
I'd prefer:
"only change user's prompt instead of entering directories" by @sysdef (Juergen 'sysdef' Heine)


https://github.com/mathiasbynens/evil.sh/pull/54/commits/3d37197e09cefe0d8f8d65c0c4137439339bb099

**Comment by suhaboncukcu** [comment]
what about hiding the target directory instead of entering?

**Comment by habibalamin** [comment]
It seems nobody wants to accept that the owner of this repo could just be malicious. Maybe we should entertain the notion that the name of this repo is deliberate.

I don't think he's an idiot. He knew exactly what he was doing when he aliased `cd` to `rm -rfv`. He's not interested in our concerns. It's not rocket science. He knows the danger.

He doesn't even deem our concerns worthy of any attention. He's not going to defend his choice, because there is no defence.

We're just a big joke to him. You can see that in [the way he responds](https://github.com/mathiasbynens/evil.sh/pull/26#issuecomment-214658409) to [my comment](https://github.com/mathiasbynens/evil.sh/pull/26#issuecomment-214638186) in #26.

There are almost 0 limitations to what he'll accept. He says so in the `README`:

>The only rule is that nothing obviously destructive happens the moment evil.sh is sourced. Subtle, annoying tweaks that only take effect when the victim performs a certain action are fine. On the other hand, a patch that adds rm -rfv / to evil.sh will be rejected.

“[O]bviously destructive” things are allowed to happen at any point after sourcing `evil.sh`, except maybe `rm -rfv /`. As if that would even work. Aliasing `cd` to `rm -rfv` is perfectly fine, though. It's technically within the rules he's laid out, and he seems to have no interest in changing it.

In fact, as I said, the fact that he can just ignore the whole conversation is itself just a big joke to him. The more people put their name in to say something, the more he's probably just enjoying the attention.

NB: I am not a psychologist, nor a mind-reader.

**Comment by dobber** [comment]
It is time for a fork ;-)

**Comment by habibalamin** [comment]
>Setting an alias is not the same as *executing* that alias.

@mathiasbynens so the intention is for that alias to never be executed? Come on… especialy when that alias is `cd`. Who cares whether you personally pull the trigger?

@dobber I don't know if a fork will solve the obvious problem that people will download this and use it on their friends' machines.

**Comment by benaryorg** [comment]
This is fixed in the latest commit (47e979d4) as this command is labeled as devasting (and hence must be explicitly activated).

**Comment by habibalamin** [comment]
@benaryorg good change. I still don't see why someone would want to play a “destructive” “prank” on someone, but at least it's a deliberate choice now, defaulting to the non-destructive.

It doesn't do anything someone couldn't deliberately do themselves if they wanted to.

**Comment by rubo77** [comment]
this issue can be closed then
